name: Publish to Azure

on:
  workflow_dispatch:
    inputs:
      target-container-SAS-token:
        description: SAS Token of target container
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download and Unzip
        shell: pwsh
        run: |
          Invoke-WebRequest 'https://raw.githubusercontent.com/kohei3110/PaaS-Management-Hands-on-Lab/master/src/Contents/PolicyDocuments.zip' -OutFile 'C:\PolicyDocuments.zip'
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\PolicyDocuments.zip', 'C:\PolicyDocuments')
      
      - name: Copy to Blob
        shell: pwsh
        run: |
          azcopy copy 'C:\PolicyDocuments\*.pdf' '${{ github.event.inputs.target-container-SAS-token }}' --recursive=true
