name: Publish to Azure

on:
  workflow_dispatch:
    inputs:
      target-policydocuments-SAS-token:
        description: SAS Token of PolicyDocument container
        required: true
      target-backpack-SAS-token:
        description: SAS Token of backpac container
        required: true

jobs:
  copy-files:
    name: Copy PDF Files to BLOB
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip
        shell: pwsh
        run: |
          Invoke-WebRequest 'https://raw.githubusercontent.com/kohei3110/PaaS-Management-Hands-on-Lab/master/src/Contents/PolicyDocuments.zip' -OutFile 'C:\PolicyDocuments.zip'
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\PolicyDocuments.zip', 'C:\PolicyDocuments')
      
      - name: Copy Policy Documents
        shell: pwsh
        run: |
          azcopy copy 'C:\PolicyDocuments\*.pdf' '${{ github.event.inputs.target-policydocuments-SAS-token }}' --recursive=true

      - name: Download file
        shell: pwsh
        run: |
          Invoke-WebRequest 'https://raw.githubusercontent.com/kohei3110/PaaS-Management-Hands-on-Lab/master/src/Contents/ContosoInsurance.bacpac'

      - name: Copy backpac file
        shell: pwsh
        run: |
          azcopy copy 'ContosoInsurance.bacpac' '${{ github.event.inputs.target-backpack-SAS-token }}'

