name: Publish to Azure

on:
  workflow_dispatch:
    inputs:
      target-container-SAS-token:
        description: SAS Token of target container
        required: true
      azure-secret:
        description: Secret (JSON)
        required: true

jobs:
  copy-files:
    name: Copy PDF Files to BLOB
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip
        shell: pwsh
        run: |
          Invoke-WebRequest 'https://raw.githubusercontent.com/kohei3110/PaaS-Management-Hands-on-Lab/master/src/Contents/PolicyDocuments.zip' -OutFile 'C:\PolicyDocuments.zip'
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\PolicyDocuments.zip', 'C:\PolicyDocuments')
      
      - name: Copy to Blob
        shell: pwsh
        run: |
          azcopy copy 'C:\PolicyDocuments\*.pdf' '${{ github.event.inputs.target-container-SAS-token }}' --recursive=true

  build-and-deploy:
    name: Build and Deploy Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ github.event.inputs.azure-secret }}
